version: '3.8'
services:
  web:
    build:
      context: ./src
      dockerfile: Dockerfile
    command: python -m uvicorn api.main:app --host ${HOST} --workers ${WORKERS} --reload
    ports:
      - "8000:8000"
    env_file: .env.dev
    volumes:
      - ./src/:/usr/src/app/
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=iclinic
      - POSTGRES_PASSWORD=iclinic
      - POSTGRES_DB=iclinic_dev

volumes:
  postgres_data:
